config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "homes/about" => "homes#about" , as: "about"
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :address_way, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :user_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(post)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def new
    if current_user.blank?
      redirect_to posts_path
    end
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit

    @post = Post.find(params[:id])

  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :address, :address_way, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
    @post = @user.post.page(params[:page]).reverse_order

  end

  def edit
    redirect_to user_path(params[:id]) if current_user.blank? || current_user.id != params[:id].to_i

    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)

  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main style="background-color: #b8860b;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="about_box">
            <h2>About</h2><br />
            <h3>
              今夜はひつまぶしは愛知県の<br />ひつまぶしのお店共有サイトです。<br />
              ひつまぶしは名古屋メシのひとつで<br />日本全国に知られています。<br />
              お店の住所とアクセス方法が<br />記載していますので<br />
              今夜のお店探しの手助けになれば幸いです。
              <br />
            </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main style="background-color: #b8860b;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="top_box">
            <h2>ようこそ、今夜はひつまぶしへ！</h2><br />
            
            <h3>
              このサイトは、ひつまぶし専門のお店共有サイトになります。<br />
              会員でない方もお店の閲覧はできますが、<br />
              お店の投稿には会員登録が必要になります。<br />
            </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hitsumabushi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <meta name="viewport" content="width=device-width, initial-sacale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm ">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">今夜はひつまぶし<i class="fas fa-fish"></i></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <i class="fas fa-user"></i><%= link_to "マイページ", user_path(current_user),class: '' %>
              </li>
              <ul>
                <i class="fas fa-store"></i><%= link_to "投稿一覧", posts_path %>
              </ul>
              <ul>
                <i class="fas fa-pen"></i><%= link_to "投稿フォーム", new_post_path %>
              </ul>
              <ul>
                <i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </ul>
            <% else %>
              <ul>
              <i class="fas fa-link"></i><%= link_to "About", about_path %>
              </ul>
              <ul>
                <i class="fas fa-store"></i><%= link_to "投稿一覧", posts_path %>
              </ul>
              <ul>
                <i class="fas fa-user-plus"></i><%= link_to "新規登録", new_user_registration_path %>
              </ul>
              <ul>
                <i class="fas fa-sign-in-alt"></i><%= link_to "ログイン", new_user_session_path %>
              </ul>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<main style="background-color: #f9f7f5;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="login-signin_box">
            <h2>投稿編集 </h2>
              <%= form_with model:@post, local:true do |f| %>
              <table class="table">
                <tr>
                  <td>タイトル</td>
                  <td><%= f.text_field :title %></td>
                </tr>
                <tr>
                  <td>説明</td>
                  <td><%= f.text_field :description %></td>
                </tr>
                <tr>
                  <td>住所</td>
                  <td><%= f.text_field :address %></td>
                </tr>
                <tr>
                  <td>アクセス方法</td>
                  <td><%= f.text_field :address_way %></td>
                </tr>
                <tr>
                  <td><%= f.submit '変更を保存する' %></td>
                </tr>
            </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/posts/index.html.erb
<main style="background-color: #f9f7f5;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="login-signin_box">
            <h2>投稿一覧 </h2>
            <% @posts.each do |post| %>
              <div class="post-item">
                <div class="image-box">
                  <div class="image">
                    <%= link_to post_path(post.id) do %>
                      <%= attachment_image_tag post, :image, :fill, 200, 200, fallback: "noimage.jpg", size:'200x200', class:"mt-3 rounded-circle" %>
                    <% end %>
                  </div>
                </div>
                <div class="title-head">
                  <table>
                    <tr>
                      <td class="title">タイトル</td>
                      <td>
                      <%= link_to post_path(post.id) do %>
                        <%= post.title %>
                      <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td class="title">ユーザー名</td>
                      <td>
                        <%= link_to user_path(post.user.id) do %>
                          <%= post.user.name %>
                        <% end %>
                        </td>
                    </tr>
                    <tr>
                      <td class="title">コメント数</td>
                      <td><%= post.post_comments.count %></td>
                    </tr>
                    <tr>
                      <td class="title">いいね数</td>
                      <td><%= post.favorites.count %></td>
                    </tr>
                  </table>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<!--ページング-->
<%= paginate @posts %>

app/views/posts/new.html.erb
<main style="background-color: #f9f7f5;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="login-signin_box">
            <h2>投稿フォーム </h2>
              <%= form_with model:@post, local:true do |f| %>
              <table class="table">
                <tr>
                  <td>タイトル</td>
                  <td><%= f.text_field :title %></td>
                </tr>
                <tr>
                  <td>説明</td>
                  <td><%= f.text_field :description %></td>
                </tr>
                <tr>
                  <td>住所</td>
                  <td><%= f.text_field :address %></td>
                </tr>
                <tr>
                  <td>アクセス方法</td>
                  <td><%= f.text_field :address_way %></td>
                </tr>
                <tr>
                  <td>画像</td>
                  <td><%= f.attachment_field :image %></td>
                </tr>
                <tr>
                  <td><%= f.submit '投稿' %></td>
                  <td>※画像以外は必須項目です</td>
                </tr>
            </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/posts/show.html.erb
<main style="background-color: #f9f7f5;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="login-signin_box">
            <h2>投稿詳細 </h2>
              <div class="post-item">
                <div class="image-box">
                  <div class="image">
                    <%= attachment_image_tag @post, :image, :fill, 200, 200, fallback: "noimage.jpg", size:'200x200', class:"mt-3 " %>
                  </div>
                </div>
                <div class="title-head">
                  <table>
                    <tr>
                      <td class="title">タイトル</td>
                      <td><%= @post.title %></td>
                    </tr>
                    <tr>
                      <td class="title">ユーザー</td>
                      <td><%= @post.user.name %></td>
                    </tr>
                    <tr>
                      <td class="title">説明</td>
                      <td><%= @post.description %></td>
                    </tr>
                    <tr>
                      <td class="title">住所</td>
                      <td> <%= @post.address %></td>
                    </tr>
                    <tr>
                      <td class="title">アクセス<br>方法</td>
                      <td><%= @post.address_way %></td>
                    </tr>
                    <tr>
                      <td class="title">コメント数</td>
                      <td><%= @post.post_comments.count %></td>
                    </tr>
                  </table>
                  <div class="fav">
                    <% if user_signed_in? %>
                      <% if @post.favorited_by?(current_user) %>
                        <p>
                          <%= link_to post_favorites_path(@post),method: :delete do %>
                            ♥<%= @post.favorites.count %> いいね
                          <% end %>
                        </p>
                      <% else %>
                      <p>
                        <%= link_to post_favorites_path(@post), method: :post do %>
                          ♡<%= @post.favorites.count %> いいね
                        <% end %>
                      </p>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                  </div>
                  <div class="comment">
                    <div>
                      <% if user_signed_in? %>
                        <div class="new_comment">
                          <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
                            <%= f.text_area :comment, row:'5' ,placheholder: "コメントをここに" %>
                            <%= f.submit "送信する" %>
                          <% end %>
                        </div>
                      <% end %>
                        </div>
                    <p>コメント</p>
                    <p>コメント件数:<%= @post.post_comments.count %></p>
                     <% @post.post_comments.each do |post_comment| %>
                      <%= post_comment.user.name %>
                      <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %></br>
                        <% if post_comment.user == current_user %>
                          <div class="comment_delete">
                            <%= link_to "コメントを削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
                          </div>
                        <% end %>
                     <% end %>
                    <div class="edit">
                      <% if @post.user == current_user %>
                        <%= link_to "投稿を編集", edit_post_path(@post) %><br />
                        <%= link_to "投稿を削除", post_path(@post), method: :delete %>
                      <% end %>
                </div>
              </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<main style="background-color: #f9f7f5;">
  <div class="padding-top: 58px;">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <div class="login-signin_box">
            <h2>プロフィール編集</h2>
            <%= form_with model:@user, local:true do |f| %>
              <div class="field">
                <%= f.label :名前 %><br />
                  <%= f.text_field :name, autofocus: true %>
              </div>
              <div class="field">
                <%= f.label :メールアドレス%><br />
                  <%= f.text_field :email %>
              </div>
              <div class="actions">
                <%= f.submit "変更を保存" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main style="background-color: #f9f7f5;">
  <div class="container">
    <div class="row">
      <div class="offset-1 col-10">
        <div class="login-signin_box">
        <% if current_user.present? && @user.id == current_user.id %>
          <div class="profile">
            <h3>
              <p>ユーザー名：<%= @user.name %></p>
              <p>メールアドレス：<%= @user.email %></p>
            </h3>
            <div>
              <%= link_to "プロフィール編集", edit_user_path(@user),class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
          <div class="users-post">
            <table class="table">
             <h4><%= @user.name %>の投稿一覧</h4>
              <tr>
                  タイトル名<br>
              </tr>
             <% @post.each do |post| %>
               <p class="post-title">
                  <%= link_to post_path(post)  do %>
                    <%= post.title %>
                  <% end %>
              </p>
             <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>